import React from 'react';
import './AIRoadmap.css';

const AIRoadmap = ({ skill, onClose }) => {
    // Simulated AI Roadmap Content
    const roadmaps = {
        'React': [
            { week: 1, title: 'Foundations & JSX', topics: ['JSX Syntax', 'Components & Props', 'State Management Basics'] },
            { week: 2, title: 'Hooks & Effects', topics: ['useEffect deep dive', 'Custom Hooks', 'Handling API Calls'] },
            { week: 3, title: 'Advanced Patterns', topics: ['Context API', 'Compound Components', 'Performance Optimization'] },
            { week: 4, title: 'Real-world Project', topics: ['Integrating Firebase', 'Unit Testing with Jest', 'Deployment'] }
        ],
        'Node.js': [
            { week: 1, title: 'Express & Middleware', topics: ['Routing', 'Request Lifecycle', 'Error Handling'] },
            { week: 2, title: 'Database & Auth', topics: ['MongoDB with Mongoose', 'JWT Authentication', 'Password Hashing'] },
            { week: 3, title: 'API Security', topics: ['Rate Limiting', 'CORS Configuration', 'Validation (Joi/Zod)'] },
            { week: 4, title: 'Scale & Performance', topics: ['Cluster Mode', 'Redis Caching', 'Dockerization'] }
        ],
        'Python': [
            { week: 1, title: 'Advanced Syntax', topics: ['Decorators', 'Generators', 'Context Managers'] },
            { week: 2, title: 'Data Analysis', topics: ['Pandas Foundations', 'NumPy Operations', 'Data Cleaning'] },
            { week: 3, title: 'Web Frameworks', topics: ['Django vs Flask', 'ORM Basics', 'REST APIs'] },
            { week: 4, title: 'Automation', topics: ['BeautifulSoup Scrapping', 'Selenium', 'Script Deployment'] }
        ]
    };

    const getRoadmapData = (skill) => {
        if (roadmaps[skill]) return roadmaps[skill];

        // Dynamic "AI Generated" Roadmap for unknown skills
        return [
            { week: 1, title: `Foundations of ${skill}`, topics: [`Understanding ${skill} Core Concepts`, `Setting Up Your Environment`, `${skill} Syntax & Basics`] },
            { week: 2, title: `Intermediate ${skill}`, topics: [`Mastering ${skill} Functions`, `Standard Libraries & Frameworks`, `Working with Data in ${skill}`] },
            { week: 3, title: `Advanced ${skill} Techniques`, topics: [`Performance Tuning in ${skill}`, `Design Patterns & Architecture`, `Security Best Practices`] },
            { week: 4, title: `Professional ${skill} Projects`, topics: [`Building a Full-Scale App`, `Testing & Debugging`, `Deployment & Maintenance`] }
        ];
    };

    const data = getRoadmapData(skill);

    return (
        <div className="roadmap-modal-overlay">
            <div className="roadmap-modal">
                <div className="roadmap-header">
                    <h2>✨ AI Learning Roadmap: {skill}</h2>
                    <button className="close-btn" onClick={onClose}>✕</button>
                </div>

                <div className="roadmap-content">
                    <p className="roadmap-intro">
                        Based on your profile, SkillBot AI has crafted this 4-week plan to help you master <strong>{skill}</strong>.
                    </p>

                    <div className="roadmap-timeline">
                        {data.map((step, idx) => (
                            <div key={idx} className="timeline-step">
                                <div className="step-number">Week {step.week}</div>
                                <div className="step-info">
                                    <h3>{step.title}</h3>
                                    <ul>
                                        {step.topics.map((t, i) => <li key={i}>{t}</li>)}
                                    </ul>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="roadmap-footer">
                    <button className="btn-save" onClick={onClose}>Add to My Goals</button>
                    <p>Generated by SkillBot AI Core v1.2</p>
                </div>
            </div>
        </div>
    );
};

export default AIRoadmap;
